// Optimized WebP images (60-80% smaller than original JPEGs)
// Generated by: npm run optimize-images
import bg0Large from 'assets/img/freepik/optimized/bg0-large.webp'
import bg1Large from 'assets/img/freepik/optimized/bg1-large.webp'
import bg2Large from 'assets/img/freepik/optimized/bg2-large.webp'
import bg3Large from 'assets/img/freepik/optimized/bg3-large.webp'
import bg4Large from 'assets/img/freepik/optimized/bg4-large.webp'
import bg5Large from 'assets/img/freepik/optimized/bg5-large.webp'
import bg6Large from 'assets/img/freepik/optimized/bg6-large.webp'

// Small versions for mobile and blur-up placeholders
import bg0Small from 'assets/img/freepik/optimized/bg0-small.webp'
import bg1Small from 'assets/img/freepik/optimized/bg1-small.webp'
import bg2Small from 'assets/img/freepik/optimized/bg2-small.webp'
import bg3Small from 'assets/img/freepik/optimized/bg3-small.webp'
import bg4Small from 'assets/img/freepik/optimized/bg4-small.webp'
import bg5Small from 'assets/img/freepik/optimized/bg5-small.webp'
import bg6Small from 'assets/img/freepik/optimized/bg6-small.webp'

// JPEG fallbacks for Safari < 14 (no WebP support)
import bg0Fallback from 'assets/img/freepik/optimized/bg0-large.jpg'
import bg1Fallback from 'assets/img/freepik/optimized/bg1-large.jpg'
import bg2Fallback from 'assets/img/freepik/optimized/bg2-large.jpg'
import bg3Fallback from 'assets/img/freepik/optimized/bg3-large.jpg'
import bg4Fallback from 'assets/img/freepik/optimized/bg4-large.jpg'
import bg5Fallback from 'assets/img/freepik/optimized/bg5-large.jpg'
import bg6Fallback from 'assets/img/freepik/optimized/bg6-large.jpg'

export type BackgroundKey = 'bg0' | 'bg1' | 'bg2' | 'bg3' | 'bg4' | 'bg5' | 'bg6'

interface BackgroundConfig {
    /** Optimized WebP for modern browsers */
    full: string
    /** Small version for blur-up placeholder effect */
    placeholder: string
    /** JPEG fallback for older browsers */
    fallback: string
}

interface Backgrounds {
    [key: string]: string
}

// Legacy export for backward compatibility
const backgrounds: Backgrounds = {
    bg0: bg0Large,
    bg1: bg1Large,
    bg2: bg2Large,
    bg3: bg3Large,
    bg4: bg4Large,
    bg5: bg5Large,
    bg6: bg6Large,
}

// Progressive loading config with placeholder support
export const backgroundsWithPlaceholders: Record<BackgroundKey, BackgroundConfig> = {
    bg0: { full: bg0Large, placeholder: bg0Small, fallback: bg0Fallback },
    bg1: { full: bg1Large, placeholder: bg1Small, fallback: bg1Fallback },
    bg2: { full: bg2Large, placeholder: bg2Small, fallback: bg2Fallback },
    bg3: { full: bg3Large, placeholder: bg3Small, fallback: bg3Fallback },
    bg4: { full: bg4Large, placeholder: bg4Small, fallback: bg4Fallback },
    bg5: { full: bg5Large, placeholder: bg5Small, fallback: bg5Fallback },
    bg6: { full: bg6Large, placeholder: bg6Small, fallback: bg6Fallback },
}

// Check WebP support
export const supportsWebP = (): boolean => {
    if (typeof document === 'undefined') return true
    const canvas = document.createElement('canvas')
    return canvas.toDataURL('image/webp').indexOf('data:image/webp') === 0
}

export default backgrounds
